# Generated by Django 5.2 on 2025-06-07 19:31

import bookings.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_alter_booking_options_booking_cancellation_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='departure_date',
            field=models.DateTimeField(default=bookings.models.get_default_departure),
        ),
    ]
