# Generated by Django 5.2.5 on 2025-08-26 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_bus_departure_date'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='booking',
            name='journey_date',
            field=models.DateField(default='2025-08-26'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together={('bus', 'seat', 'journey_date', 'status')},
        ),
    ]
