# Generated by Django 5.2.5 on 2025-08-26 18:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0008_alter_booking_unique_together_booking_journey_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='seat',
            name='is_booked',
        ),
        migrations.RemoveField(
            model_name='seat',
            name='last_booked_at',
        ),
        migrations.RemoveField(
            model_name='seat',
            name='last_booked_by',
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'confirmed')), fields=('bus', 'seat', 'journey_date'), name='unique_confirmed_seat_per_date'),
        ),
    ]
