# Generated by Django 5.2.5 on 2025-08-26 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0009_alter_booking_unique_together_remove_seat_is_booked_and_more'),
    ]

    operations = [
    ]
