# Generated by Django 5.2.5 on 2025-08-27 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0010_auto_20250826_1852'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seat',
            options={'ordering': ['seat_number']},
        ),
        migrations.RemoveConstraint(
            model_name='booking',
            name='unique_confirmed_seat_per_date',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='seat',
        ),
        migrations.AddField(
            model_name='booking',
            name='seats',
            field=models.ManyToManyField(related_name='bookings', to='bookings.seat'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='bus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='bookings.bus'),
        ),
        migrations.AlterField(
            model_name='bus',
            name='features',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='bus',
            name='no_of_seats',
            field=models.PositiveIntegerField(),
        ),
    ]
